#####################################
# +-------------------------------+ #
# | AdvancedAutoSmelt - By Pulsi_ | #
# +-------------------------------+ #
#####################################

# Check for updates.
Update-Checker: true

# Automatically update the files when there is a new update.
Auto-Update: true

# Permission to toggle auto pickup: advancedautosmelt.toggle.autopickup
AutoPickup:
  # Enable or not this option.
  Enabled: true

  # It will be enabled even if it doesn't have the toggle permission.
  Enable-On-Join:
    Enabled: true
    # Choose if a player needs to have the specified
    # permission to enable the autopickup when joining.
    Is-Required-Permission: false
    Permission: "your.permission.here"

  # To make this plugin compatible with some
  # plugins like MCMMO, enable this option.
  Process-PlayerPickupEvent: false

  # Choose if dropping items on the ground
  # when the inventory is full or not.
  # If disabled, the items that should normally
  # go out the inventory will be destroyed.
  Drop-Items-On-Inventory-Full: true

  # This option will make the plugin check the item used to break the block.
  # This will automatically enable silk touch support
  # and won't give drops if breaking a block with an
  # item that won't break it normally (example: diamond ore with wooden pickaxe)
  Check-Fot-Item-In-Hand: true

  # The worlds where autopickup won't work.
  World-Blacklist:
    - "World1"
    - "World2"

  # The blocks that won't be affected by autopickup.
  Block-Blacklist:
    - "SKULL"

# Permission to toggle auto smelt: advancedautosmelt.toggle.autosmelt
AutoSmelt:
  Enabled: true

  # It will be enabled even if it doesn't have the toggle permission.
  Enable-On-Join:
    Enabled: true
    Is-Required-Permission: false
    Permission: "your.permission.here"

  # Format: Original-Drop-Material;New-Drop-Material
  Smelt-List:
    - "COBBLESTONE;STONE"
    - "IRON_ORE;IRON_INGOT"
    - "GOLD_ORE;GOLD_INGOT"

  # The worlds where autosmelt won't work.
  World-Blacklist:
    - "World1"
    - "World2"

Fortune:
  # Enable the fortune support, this will
  # multiply the items picked based on your
  # fortune level.
  # Fortune works for picked-up and non blocks.
  Enabled: true

  Is-Required-Permission:
    Enabled: true
    Permission: "advancedautosmelt.fortune"

  Block-Whitelist:
    # Enable the block whitelist.
    # NOTE: If enabled, only the listed blocks
    # will be affected from fortune.
    Enabled: true

    # This will reverse the list, and won't
    # make fortune affect the listed blocks.
    Whitelist-Is-Blacklist: false

    Whitelist:
      - "STONE"
      - "IRON_ORE"
      - "GOLD_ORE"

  # The worlds where fortune won't work.
  World-Blacklist:
    - "World1"
    - "World2"

# Permission to toggle auto sell: advancedautosmelt.toggle.autosell
AutoSell:
  # Auto sell is a useful feature where you can sell every type of item for a price.
  # You can choose in which economy the money will be deposited in the lower part of this config.
  #
  # IMPORTANT! READ ME: To avoid confusion.
  # The auto sell will be processed after auto smelt and fortune modules.
  # This means that if you mine, for example, COAL_ORE, that is then smelted
  # into COAL, and multiplied by fortune, auto sell will sell COAL and not COAL_ORE.
  #
  # Auto sell won't sell items that are not present in the file "sell_prices.yml"
  # This module support PrisonEnchants explosions, so no worries ;).
  Enabled: false

  # If this option is enabled, auto sell will automatically sell any
  # item as soon as you get them, they won't be shown in the inventory.
  Instant-Sell: false

  # If "Instant-Sell" is disabled, you can choose if automatically
  # sell all the items in the inventory when it's full when you
  # try to mine another block.
  Sell-On-Inventory-Full: true

  # If you want to make the sell system use a cmd to manually sell
  # items, enable this option and the /sellall cmd will be
  # registered to the server, otherwise, it won't be registered.
  # This option will need to restart the server to apply changes.
  Register-Sell-All-Cmd: false

  # Automatically detect server economy and add money using Vault.
  Use-Vault-Economy: true

  # If "Use-Vault-Economy" is disabled, you will be able to add money
  # to the player using the custom cmd that will be run when selling.
  #
  # Cmd placeholders: %player% -> Player name. %amount% -> Money amount.
  Custom-Add-Cmd: "eco give %player% %amount%"

  # It will be enabled even if it doesn't have the toggle permission.
  Enable-On-Join:
    Enabled: true
    Is-Required-Permission: false
    Permission: "your.permission.here"

# CustomExp feature
Custom-Exp:
  Enabled: true

  # Format: BrokenBlock;AmountOfExp (Do not use decimal numbers.)
  #
  # [NEED_AUTOSMELT] means that the block will give 3 exp
  # only if the player is able to autosmelt.
  # (It is useful when the player doesn't have the autosmelt
  # enabled, and we want to give him extra exp only when
  # "smelting" the iron ore)
  Exp-List:
    - "STONE;1"
    - "IRON_ORE;3[NEED_AUTOSMELT]"
    - "GOLD_ORE;5[NEED_AUTOSMELT]"

  # The worlds where custom exp won't work.
  World-Blacklist:
    - "World1"
    - "World2"

# Cool feature to warning players when they
# mine while having the inventory full.
Inventory-Full-Alerts:
  # Disable this to disable all features.
  Enabled: true

  Title:
    Enabled: true
    Title: "&c&lWARNING!,&aYour inventory is full!" # Title,SubTitle

  Sound:
    Enabled: true
    Sound: "BLOCK_NOTE_BLOCK_PLING 5 1" # SoundType Volume Pitch

  Actionbar:
    Enabled: true
    Message: "&c&lWARNING! &aYour inventory is full!"

  Message:
    Enabled: true
    Message:
      - ""
      - "      &c&lWARNING!"
      - "&aYour inventory is full!"
      - ""

  # In ticks ( 20 ticks -> 1 second )
  Alert-Delay: 60

Extras:
  Inventory-Smelter:
    # Transform blocks in others
    # Permission required: advancedautosmelt.inventory-smelter
    Enabled: false

    List: # Block in the inventory;New transformed block
      - "COBBLESTONE;STONE"
      - "IRON_ORE;IRON_INGOT"

  Ingot-To-Block:
    # Permission required: advancedautosmelt.ingot-to-block
    Enabled: false

    # Item(x);Result(y)
    # Every 9 x you get 1 y.
    List:
      - "IRON_INGOT;IRON_BLOCK"
      - "GOLD_INGOT;GOLD_BLOCK"

Placeholders:
  Enabled: "&2Enabled"
  Disabled: "&cDisabled"

# Do not edit this if you don't know what it does.
# Choose one listener priority for the block break event of AAS between:
# - HIGHEST
# - HIGH
# - NORMAL
# - LOW
# - LOWEST
Block-Break-Listener-Priority: "NORMAL"

# If you have worldguard installed, hook into it to
# check for regions where the player can't break
# blocks to avoid any bugs.
WorldGuard-Hook: true

# Do never edit this for any reasons or the config may get reset.
Config-Version: 5.0.3