##################################################################
#                           _        _____                _ _    #
#      /\        /\        | |      / ____|              | | |   #
#     /  \      /  \  _   _| |_ ___| (___  _ __ ___   ___| | |_  #
#    / /\ \    / /\ \| | | | __/ _ \\___ \| '_ ` _ \ / _ \ | __| #
#   / ____ \  / ____ \ |_| | || (_) |___) | | | | | |  __/ | |_  #
#  /_/    \_\/_/    \_\__,_|\__\___/_____/|_| |_| |_|\___|_|\__| #
#                                                                #
# Author: Pulsi_                                                 #
# Thanks for using this plugin!                                  #
#                                                                #
##################################################################

#Receive updates messages when there is a new Update available
Update-Checker: true

#If your server is on 1.12.2 or more, you should put this option to false
Enable-Legacy-Support: true

######################################################
#                   < AUTOSMELT >                    #
######################################################
AutoSmelt:

  #Disable the autosmelt in creative mode, this will avoid the possibility of dupe blocks
  Disable-Creative-Mode: true

  #Automatically smelt Iron Ore -> Permission: advancedautosmelt.smelt.iron
  Smelt-Iron: true
  #Give or not the experience when breaking an Iron Ore Block
  Give-Exp-Iron: true
  #Give to the Player some Experience for Mining Iron Ores
  Iron-Exp: 1

  #Automatically smelt Gold Ore -> Permission: advancedautosmelt.smelt.gold
  Smelt-Gold: true
  #Give or not the experience when breaking an Iron Ore Block
  Give-Exp_Gold: true
  #Give to the Player some Experience for Mining Gold Ores
  Gold-Exp: 2

  #The stone will be mined like silk touch -> advancedautosmelt.smelt.stone
  Smelt-Stone: true

  #Instead of give Obsidian, it will give the EnderChest when broken
  Smelt-Enderchest: true

  #This will smelt ores not smelted in the Inventory
  Smelt-Ores-In-Inventory: true
  Inv-Smelt:
    #Smelt Iron Ores in the Inventory
    Iron-Ore: true

    #Smelt Gold Ores in the Inventory
    Gold-Ore: true

    #Smelt Cobblestone in the Inventory
    Cobblestone: true


######################################################
#                   < AUTOPICKUP >                   #
######################################################
AutoPickup:

  #Should the plugin enable this Option? -> Permission: advancedautosmelt.autopickup
  Enable-Autopickup: true

  #The player will directly receive Experience -> Permission: advancedautosmelt.autopickupexp
  Autopickup-Experience: true

  #Make the blocks broken don't drop in the ground when the inventory is full
  Inv-Full-Drop-Items: true


######################################################
#                    < FORTUNE >                     #
######################################################
Fortune:

  #Enable the fortune feature, this will give extra blocks based on your fortune level -> Permission: advancedautosmelt.fortune
  Enable-Fortune-Support: true

  #Enabling the fortune support for silktouch feature, this will give extra blocks based on
  #your fortune level, but supporting Silk Touch
  Fortune-Support-Silktouch: false

  #Use the block whitelist
  Use-Whitelist: true
  #This will work with blocks too
  Whitelist:
    - IRON_ORE
    - COAL_ORE
    - LAPIS_ORE
    - DIAMOND_ORE
    - EMERALD_ORE
    - GOLD_ORE
    - REDSTONE_ORE


######################################################
#                < INVENTORY FULL >                  #
######################################################
InventoryFull:

  #Enable this to activate the inventory full alerts!
  Inventory-Full-Alert: true

  #Send a title on InventoryFull
  Title:
    Use-Title: true
    Title: "&c&lWarning!"
    Sub-Title: "&7Your inventory is full!"

  #Send the actionbar message on InventoryFull
  Actionbar:
    Use-Actionbar: true
    Message: "&c&lWarning! &7Your inventory is full!"

  #Send messages on InventoryFull
  Messages:
    Use-Messages: true
    Messages:
      - "&8&m----*----------------------*----"
      - "&c&lAlert! &7Your inventory is full!"
      - "     &cYou are losing Items!"
      - "&8&m----*----------------------*----"

  #Play a sound on Inventory Full
  Sound:
    Use-Sound: true
    Sound-Type: 'BLOCK_ANVIL_BREAK'
    Volume: 2
    Pitch: 1

  #The delay between alerts, in ticks
  Alert-Delay: 50


######################################################
#                < CUSTOM PICKAXE >                  #
######################################################
Custom-Pickaxe:

  Works-only-with-custom-pickaxe: false
  Pickaxe:
    Material-Type: DIAMOND_PICKAXE
    Display-Name: "&2&lSmelter &d&lPickaxe"
    Use-Lore: true
    Lore:
      - "&aThe magic Smelter Pickaxe"
      - "&dFound in one of the rares mine!"
    Glowing: true


######################################################
#                  < BLACKLISTS >                    #
######################################################
Disabled-Worlds:
  - example1
  - example2

#The blocks in this list won't work with anything, fortune, autopickup, etc..
Disabled-Blocks:
  - SKULL