#####################################
# +-------------------------------+ #
# | AdvancedAutoSmelt - By Pulsi_ | #
# +-------------------------------+ #
#####################################

Update-Checker: true

# The main plugin prefix, that will be
# displayed before messages and commands.
Prefix: "&8[&a&lA&9&lA&c&lS&8] "

# AutoPickup options.
AutoPickup:
  # Enable or not this option.
  Enabled: true

  # Choose if making players enabling
  # autopickup automatically on join.
  Enabled-On-Join:
    Enabled: true
    # Choose if a player needs to have the specified
    # permission to enable the autopickup when joining.
    Is-Required-Permission: false
    Permission: "your.persmission.here"

  # If your server version is 1.12.2
  # or higher, disable this option.
  Enable-Legacy-Support: true

  # To make this plugin compatible with some
  # plugins like MCMMO, enable this option.
  Process-PlayerPickupEvent: false

  # Choose if dropping items on ground
  # when the inventory is full or not.
  Drop-Items-On-Inventory-Full: true

  # The plugin will check for the player
  # item and will give drops only if the
  # block can be broken from that item.
  # ( Usually used to avoid things like
  # getting stone or minerals with hands )
  Drops-Need-Correct-Item: true

  # The worlds where autopickup won't work.
  World-Blacklist:
    - "World1"
    - "World2"

  # The blocks that won't be affected by autopickup.
  Block-Blacklist:
    - "SKULL"

# AutoSmelt options.
AutoSmelt:
  Enabled: true

  Enabled-On-Join:
    Enabled: true
    Is-Required-Permission: false
    Permission: "your.persmission.here"

  Smelt-List:
    # Block-Broken;Drop-Given
    - "STONE;STONE"
    - "IRON_ORE;IRON_INGOT"
    - "GOLD_ORE;GOLD_INGOT"

  # The worlds where autosmelt won't work.
  World-Blacklist:
    - "World1"
    - "World2"

Fortune:
  # Enable the fortune support, this will
  # multiply the items picked based on your
  # fortune level. It will work for picked-up
  # and not picked-up blocks.
  Enabled: true

  Is-Required-Permission:
    Enabled: true
    Permission: "advancedautosmelt.fortune"

  Block-Whitelist:
    # Enable the block whitelist.
    # NOTE: If enabled, only the listed blocks
    # will be affected from fortune.
    Enabled: true

    # This will reverse the list, and won't
    # make fortune affect the listed blocks.
    Whitelist-Is-Blacklist: false

    Whitelist:
      - "STONE"
      - "IRON_ORE"
      - "GOLD_ORE"

  # The worlds where fortune won't work.
  World-Blacklist:
    - "World1"
    - "World2"

# CustomExp feature
Custom-Exp:
  Enabled: true
  Exp-List:
    # BrokenBlock;AmountOfExp
    # Do not use decimal numbers.
    - "STONE;1"
    - "IRON_ORE;3"
    - "GOLD_ORE;5"

  # The worlds where custom exp won't work.
  World-Blacklist:
    - "World1"
    - "World2"

# Cool feature to warning players when they
# mine while having the inventory full.
Inventory-Full-Alerts:
  # Disable this to disable all features.
  Enabled: true

  Title:
    Enabled: true
    Title: "&c&lWARNING!,&aYour inventory is full!" # Title,SubTitle

  Sound:
    Enabled: true
    Sound: "BLOCK_NOTE_BLOCK_PLING 5 1" # SoundType Volume Pitch

  Actionbar:
    Enabled: true
    Message: "&c&lWARNING! &aYour inventory is full!"

  Message:
    Enabled: true
    Message:
      - ""
      - "      &c&lWARNING!"
      - "&aYour inventory is full!"
      - ""

  # In seconds
  Alert-Delay: 3

Extras:
  Inventory-Smelter:
    # Transform blocks in others
    Enabled: true
    List:
      # Block in the invetory;New transformed block
      - "COBBLESTONE,STONE"
      - "IRON_ORE;IRON_INGOT"

  Ingot-To-Block:
    Enabled: true
    List:
      # Item(x);Result(y)
      # Every 9 x you get 1 y.
      - "IRON_INGOT;IRON_BLOCK"
      - "GOLD_INGOT;GOLD_BLOCK"