# AdvancedAutoSmelt FileConfiguration

# Receive updates messages when there is a new Update available
Update-Checker: true

Prefix: "&8&l<&d&lAdvanced&a&lAuto&c&lSmelt&8&l> "

# If your server is on 1.12.2 or more, you should put this option to false
Enable-Legacy-Support: true
# The plugin won't affect players in creative mode
Disable-Creative-Mode: true
# Worlds where the plugin won't affect
Disabled-Worlds:
  - example1
  - example2
# Blocks where the plugin won't affect
Disabled-Blocks:
  - SKULL

AutoSmelt:
  Enabled: true
  # The list of all blocks that will be smelted
  # you can edit it as you want.
  #
  # The block broken;The block drop
  Smelt-List:
    - IRON_ORE;IRON_INGOT
    - GOLD_ORE;GOLD_INGOT
    - STONE;STONE
  # This features allow you to automatically
  # smelt the items that are in your inventory
  Inventory-Smelt:
    Enabled: true
    Smelt-List:
      - COBBLESTONE;STONE
      - IRON_ORE;IRON_INGOT
      - GOLD_ORE;GOLD_INGOT

# The autopickup will automatically pickup the blocks mined
AutoPickup:
  # Enabled or not this feature
  Enabled: true
  # Drop items when the inventory is full.
  # This will prevent the destruction of
  # some mines blocks when having a full inventory
  Inv-Full-Drop-Items: true
  # Enabling this feature will make the plugin
  # process the ItemPickupEvent, to support plugins
  # like MCMMO
  Process-Pickup-Event: false
  # This feature will give a custom amount of
  # experience for every block mined.
  #
  # The block mined;The exp received
  Custom-Exp:
    Enabled: true
    Exp-List:
      - IRON_ORE;2
      - GOLD_ORE;3
      - STONE;1

Fortune:
  # Enable the fortune feature, this will give extra blocks based on your fortune level
  Enable-Fortune-Support: true
  Whitelist:
    # Enabling this option, only the blocks in the whitelist
    # will be affect by fortune
    Enabled: true
    # This will work with blocks too
    Block-List:
      - IRON_ORE
      - COAL_ORE
      - LAPIS_ORE
      - DIAMOND_ORE
      - EMERALD_ORE
      - GOLD_ORE
      - REDSTONE_ORE

InventoryAlerts:
  # Enable this to activate the inventory full alerts
  Enabled: true

  # Send a title
  Title:
    Enabled: true
    Title: "&c&lWarning!,&7Your inventory is full!"

  # Send the actionbar message
  Actionbar:
    Enabled: true
    Message: "&c&lWarning! &7Your inventory is full!"

  # Send messages
  Messages:
    Enabled: true
    Messages:
      - "&8&m----*----------------------*----"
      - "&c&lAlert! &7Your inventory is full!"
      - "     &cYou are losing Items!"
      - "&8&m----*----------------------*----"

  #Play a sound on Inventory Full
  Sound:
    Enabled: true
    Sound-Type: "BLOCK_ANVIL_BREAK 2 1"

  #The delay between alerts, in ticks
  Alert-Delay: 50