#####################################
# +-------------------------------+ #
# | AdvancedAutoSmelt - By Pulsi_ | #
# +-------------------------------+ #
#####################################

# Check for updates.
Update-Checker: true

# Automatically update the files when there is a new update.
Auto-Update: true

# AutoPickup options.
AutoPickup:
  # Enable or not this option.
  Enabled: true

  # Choose if making players enabling
  # autopickup automatically on join.
  Enable-On-Join:
    Enabled: true
    # Choose if a player needs to have the specified
    # permission to enable the autopickup when joining.
    Is-Required-Permission: false
    Permission: "your.permission.here"

  # To make this plugin compatible with some
  # plugins like MCMMO, enable this option.
  Process-PlayerPickupEvent: false

  # Choose if dropping items on the ground
  # when the inventory is full or not.
  # If disabled, the items that should normally
  # go out the inventory will be destroyed.
  Drop-Items-On-Inventory-Full: true

  # This option will make the plugin check the item used to break the block.
  # This will automatically enable silk touch support
  # and won't give drops if breaking a block with an
  # item that won't break it normally (example: diamond ore with wooden pickaxe)
  Check-Fot-Item-In-Hand: true

  # The worlds where autopickup won't work.
  World-Blacklist:
    - "World1"
    - "World2"

  # The blocks that won't be affected by autopickup.
  Block-Blacklist:
    - "SKULL"

# AutoSmelt options.
AutoSmelt:
  Enabled: true

  Enable-On-Join:
    Enabled: true
    Is-Required-Permission: false
    Permission: "your.permission.here"

  # Format: Original-Drop-Material;New-Drop-Material
  Smelt-List:
    - "COBBLESTONE;STONE"
    - "IRON_ORE;IRON_INGOT"
    - "GOLD_ORE;GOLD_INGOT"

  # The worlds where autosmelt won't work.
  World-Blacklist:
    - "World1"
    - "World2"

Fortune:
  # Enable the fortune support, this will
  # multiply the items picked based on your
  # fortune level. It will work for picked-up
  # and not picked-up blocks.
  Enabled: true

  Is-Required-Permission:
    Enabled: true
    Permission: "advancedautosmelt.fortune"

  Block-Whitelist:
    # Enable the block whitelist.
    # NOTE: If enabled, only the listed blocks
    # will be affected from fortune.
    Enabled: true

    # This will reverse the list, and won't
    # make fortune affect the listed blocks.
    Whitelist-Is-Blacklist: false

    Whitelist:
      - "STONE"
      - "IRON_ORE"
      - "GOLD_ORE"

  # The worlds where fortune won't work.
  World-Blacklist:
    - "World1"
    - "World2"

# CustomExp feature
Custom-Exp:
  Enabled: true

  # Format: BrokenBlock;AmountOfExp (Do not use decimal numbers.)
  #
  # [NEED_AUTOSMELT] means that the block will give 3 exp
  # only if the player is able to autosmelt.
  # (It is useful when the player doesn't have the autosmelt
  # enabled, and we want to give him extra exp only when
  # "smelting" the iron ore)
  Exp-List:
    - "STONE;1"
    - "IRON_ORE;3[NEED_AUTOSMELT]"
    - "GOLD_ORE;5[NEED_AUTOSMELT]"

  # The worlds where custom exp won't work.
  World-Blacklist:
    - "World1"
    - "World2"

# Cool feature to warning players when they
# mine while having the inventory full.
Inventory-Full-Alerts:
  # Disable this to disable all features.
  Enabled: true

  Title:
    Enabled: true
    Title: "&c&lWARNING!,&aYour inventory is full!" # Title,SubTitle

  Sound:
    Enabled: true
    Sound: "BLOCK_NOTE_BLOCK_PLING 5 1" # SoundType Volume Pitch

  Actionbar:
    Enabled: true
    Message: "&c&lWARNING! &aYour inventory is full!"

  Message:
    Enabled: true
    Message:
      - ""
      - "      &c&lWARNING!"
      - "&aYour inventory is full!"
      - ""

  # In ticks ( 20 ticks -> 1 second )
  Alert-Delay: 60

Extras:
  Inventory-Smelter:
    # Transform blocks in others
    # Permission required: advancedautosmelt.inventory-smelter
    Enabled: false

    List: # Block in the inventory;New transformed block
      - "COBBLESTONE;STONE"
      - "IRON_ORE;IRON_INGOT"

  Ingot-To-Block:
    # Permission required: advancedautosmelt.ingot-to-block
    Enabled: false

    # Item(x);Result(y)
    # Every 9 x you get 1 y.
    List:
      - "IRON_INGOT;IRON_BLOCK"
      - "GOLD_INGOT;GOLD_BLOCK"

Placeholders:
  Enabled: "&2Enabled"
  Disabled: "&cDisabled"

# Do not edit this if you don't know what it does.
# Choose one listener priority for the block break event of AAS between:
# - HIGHEST
# - HIGH
# - NORMAL
# - LOW
# - LOWEST
Block-Break-Listener-Priority: "NORMAL"

# If you have worldguard installed, hook into it to
# check for regions where the player can't break
# blocks to avoid any bugs.
WorldGuard-Hook: true

# Do never edit this for any reasons or the config may get reset.
Config-Version: 5.0.2