name: AdvancedAutoSmelt
version: '${version}'
main: me.pulsi_.advancedautosmelt.AdvancedAutoSmelt
api-version: 1.13
load: STARTUP
authors: [ Pulsi_ ]
commands:
  advancedautosmelt:
    aliases: [aas]

  autopickup:
    usage: "/autopickup"

  autosmelt:
    usage: "/autosmelt"

  inventoryalerts:
    usage: "/inventoryalerts"