name: AdvancedAutoSmelt
version: '${version}'
main: me.pulsi_.advancedautosmelt.AdvancedAutoSmelt
api-version: 1.13
load: STARTUP
softdepend:
  - PlaceholderAPI
  - PrisonEnchants
  - Vault
authors: [ Pulsi_ ]
commands:
  advancedautosmelt:
    aliases: [aautosmelt, autosmelt, aas]

  autopickup:
    usage: "/autopickup"

  autosmelt:
    usage: "/autosmelt"

  autosell:
    usage: "/autosell"

  inventoryalerts:
    usage: "/inventoryalerts"

  sellall:
    usage: "/sellall"