name: AdvancedAutoSmelt
version: 3.0.0
main: me.pulsi_.advancedautosmelt.AdvancedAutoSmelt
api-version: 1.13
load: STARTUP
authors: [ Pulsi_ ]
description: The best AutoPickup / AutoSmelt plugin on Spigot with a lot more features!
commands:
  advancedautosmelt:
    aliases: [autosmelt, as]