name: AdvancedAutoSmelt
version: '${version}'
main: me.pulsi_.advancedautosmelt.AdvancedAutoSmelt
api-version: 1.13
load: STARTUP
softdepend:
  - PlaceholderAPI
  - Vault
authors: [ Pulsi_ ]
commands:
  advancedautosmelt:
    aliases: [aautosmelt, autosmelt, aas]

  autopickup:

  autosmelt:

  autosell:

  inventoryalerts:

  sellall: